{{- if .Values.gateway.enable -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "{{ .Values.app }}-internal-gateway"
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "{{ .Values.gateway.host }}"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.app }}-internal-gateway-vs"
spec:
  hosts:
      - "{{ .Values.gateway.host }}"
  gateways:
    - "{{ .Values.app }}-internal-gateway"
  http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          port:
            number: 80
          host: {{ .Values.app }}
{{- end -}}